dataset:
  bids_root: "BIDS"
  task: "VCV"
  subjects: ["01", "02","03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14"]
  #subjects: ["04", "02"]
  datatype: "eeg"




preprocessing:
  l_freq: 0.5
  h_freq: 30.0
  resample_freq: None
  tmin: -0.2
  tmax: 1.0
  baseline: [-0.2, 0.0]


decoding_type: Words # Syllables



model:
  name: "EEGNetv4" # Options: EEGConformer, EEGNetv4, ShallowFBCSPNet, Deep4Net
  n_classes: 50 # Assuming some number of VCV classes, to be adapted
  in_chans: 64 # Check dataset specific channel count
  input_window_samples: 1200 # (tmax - tmin) * resample_freq

training:
  batch_size: 256
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  device: "cuda" # or "cpu"


workflow:
  create_syllable_epochs: False
  create_words_epochs: false
  
