dataset:
  bids_root: "../BIDS"
  task: "VCV"
  subjects: ["03"]
  datatype: "eeg"

preprocessing:
  l_freq: 1.0
  h_freq: 100.0
  resample_freq: 250
  tmin: -0.2
  tmax: 1.0
  baseline: [-0.2, 0.0]

model:
  name: "EEGConformer"
  n_classes: 24
  in_chans: 64
  input_window_samples: 300

training:
  batch_size: 4
  epochs: 1
  lr: 0.001
  weight_decay: 0.0001
  device: "cuda"
